project:
  type: default
  title: "neuro2"
  execute-dir: project
  render:
    - template.qmd

format:
  # neurotyp-adult-typst:
  #   keep-typ: true
  #   keep-md: true
  #   papersize: "us-letter"
  #   bodyfont: "IBM Plex Serif"
  #   sansfont: "IBM Plex Sans"
  #   fontsize: 12pt
  #   number-sections: false
  #   number-offset: 1
  #   shift-heading-level-by: 0
  #   citeproc: true
  #   csl: inst/resources/bib/apa.csl
  #   reference-location: document
  #   bibliography: inst/resources/bib/refs.bib
  #   fig-width: 6
  #   fig-height: 4
  #   fig-format: svg

  neurotyp-forensic-typst:
    keep-typ: true
    keep-md: true
    papersize: "us-letter"
    bodyfont: "IBM Plex Serif"
    sansfont: "IBM Plex Sans"
    fontsize: 12pt
    number-sections: false
    number-offset: 1
    citeproc: true
    csl: inst/resources/bib/apa.csl
    reference-location: document
    bibliography: inst/resources/bib/refs.bib
    shift-heading-level-by: 0
    fig-width: 6
    fig-height: 4
    fig-format: svg

  # neurotyp-pediatric-typst:
  #   keep-typ: true
  #   keep-md: true
  #   papersize: "us-letter"
  #   bodyfont: "IBM Plex Serif"
  #   sansfont: "IBM Plex Sans"
  #   fontsize: 12pt
  #   number-sections: false
  #   number-offset: 1
  #   citeproc: true
  #   csl: inst/resources/bib/apa.csl
  #   reference-location: document
  #   bibliography: inst/resources/bib/refs.bib
  #   shift-heading-level-by: 0
  #   fig-width: 6
  #   fig-height: 4
  #   fig-format: svg

execute:
  warning: false
  echo: false
  message: false
  freeze: auto
  cache: true
  engine: knitr
  tools:
    r: "/usr/local/bin/R"

editor:
  markdown:
    wrap: sentence
    canonical: true
fig-width: 6
fig-asp: 0.618
out-width: 70%
fig-align: center
fig-format: svg
fig-dpi: 270
df-print: kable
