project:
  type: default
  title: "neuro2"
  execute-dir: project
  pre-render:
    - R/quarto_helpers.R
    - generate_domain_files.R
    - generate_all_domain_assets.R
    # Removed generate_domain_outputs.R - no longer needed
  render:
    - template.qmd

# ...existing metadata and format sections...

metadata-files:
  - _variables.yml

format:
  neurotyp-adult-typst:
    keep-typ: true
    keep-md: true
    papersize: "a4"
    bodyfont: "Source Serif 4"
    sansfont: "Source Sans 3"
    fontsize: 11pt
    number-sections: false
    number-offset: 1
    shift-heading-level-by: 0
    citeproc: true
    csl: inst/resources/bib/apa.csl
    reference-location: document
    bibliography: inst/resources/bib/refs.bib
    fig-width: 6
    fig-height: 4
    fig-format: svg

  neurotyp-forensic-typst:
    keep-typ: true
    keep-md: true
    papersize: "us-letter"
    bodyfont: "IBM Plex Serif"
    sansfont: "IBM Plex Sans"
    fontsize: 12pt
    number-sections: false
    number-offset: 1
    citeproc: true
    csl: inst/resources/bib/apa.csl
    reference-location: document
    bibliography: inst/resources/bib/refs.bib
    shift-heading-level-by: 0
    fig-width: 6
    fig-height: 4
    fig-format: svg

  neurotyp-pediatric-typst:
    keep-typ: true
    keep-md: true
    papersize: "us-letter"
    bodyfont: "IBM Plex Serif"
    sansfont: "IBM Plex Sans"
    fontsize: 11pt
    number-sections: false
    number-offset: 1
    citeproc: true
    csl: inst/resources/bib/apa.csl
    reference-location: document
    bibliography: inst/resources/bib/refs.bib
    shift-heading-level-by: 0
    fig-width: 6
    fig-height: 4
    fig-format: svg

  typst:
    keep-typ: true
    keep-md: true
    papersize: "us-letter"
    bodyfont: "IBM Plex Serif"
    sansfont: "IBM Plex Sans"
    fontsize: 11pt
    number-sections: false
    number-offset: 1
    citeproc: true
    csl: inst/resources/bib/apa.csl
    reference-location: document
    bibliography: inst/resources/bib/refs.bib
    shift-heading-level-by: 0
    fig-width: 6
    fig-height: 4
    fig-format: svg

execute:
  warning: false
  echo: false
  eval: true
  message: false
  freeze: auto
  cache: true
  engine: knitr
  tools:
    r: "/usr/local/bin/R"

editor:
  markdown:
    wrap: sentence
    canonical: true
fig-width: 6
fig-asp: 0.618
out-width: 70%
fig-align: center
fig-format: svg
fig-dpi: 270
df-print: kable
