patient:
  name: "Biggie"
  age: 35.0
  doe: "2025-07-21"
data:
  input_dir: data-raw/csv
  output_dir: data
  format: parquet
processing:
  use_duckdb: yes
  parallel: yes
report:
  template: template.qmd
  format: neurotyp-adult-typst
  output_dir: output
