# Fixed analysis script template
# This replaces the broken version in setup_patient_workspace()

create_fixed_analysis_script <- function(patient_name, assessment_date) {
  sprintf('
# Neuropsychological Assessment Analysis for %s
# Generated by neuro2 package on %s

library(neuro2)
library(here)
library(yaml)

# Load configuration
config <- yaml::read_yaml("config.yml")

# Main analysis function
main_analysis <- function() {
  
  message("🧠 Starting assessment analysis for ", config$patient$name)
  
  # Step 1: Load and validate data (FIXED - now uses actual function)
  message("📊 Loading and validating data...")
  data_files <- validate_and_load_data(
    data_dir = config$data$input_dir,
    config = config,
    verbose = config$processing$verbose
  )
  
  # Check if we have any data
  if (length(data_files) == 0) {
    stop("No valid data files found. Please check your data directory.")
  }
  
  # Step 2: Get available domains
  message("🔍 Discovering available domains...")
  available_domains <- get_available_domains(
    data_files, 
    verbose = config$processing$verbose
  )
  
  if (length(available_domains) == 0) {
    stop("No domains found in data. Please check your data format.")
  }
  
  # Step 3: Process all domains
  message("🧠 Processing domains: ", paste(available_domains, collapse = ", "))
  results <- process_all_domains(
    data_dir = config$data$input_dir,
    age_group = config$patient$age_group,
    verbose = config$processing$verbose
  )
  
  # Step 4: Generate report
  message("📄 Generating assessment report...")
  report_path <- generate_assessment_report(
    results = results,
    patient_info = config$patient,
    output_dir = config$data$output_dir,
    format = config$output$format
  )
  
  message("✅ Analysis complete! Report: ", report_path)
  message("📁 Generated files:")
  
  # List generated files
  if (dir.exists("figs")) {
    fig_files <- list.files("figs", pattern = "\\.(png|pdf)$")
    if (length(fig_files) > 0) {
      message("  📊 Figures: ", paste(fig_files, collapse = ", "))
    }
  }
  
  if (dir.exists("output")) {
    output_files <- list.files("output", pattern = "\\.(pdf|html|qmd)$")
    if (length(output_files) > 0) {
      message("  📄 Reports: ", paste(output_files, collapse = ", "))
    }
  }
  
  return(list(
    report_path = report_path,
    results = results,
    data_files = data_files
  ))
}

# Error handling wrapper
safe_main_analysis <- function() {
  tryCatch({
    main_analysis()
  }, error = function(e) {
    message("❌ Analysis failed with error: ", e$message)
    message("🔧 Troubleshooting tips:")
    message("  1. Check that your data files are in the data/ directory")
    message("  2. Verify data format matches requirements (see data/README.md)")
    message("  3. Ensure config.yml is properly configured")
    message("  4. Run: validate_and_load_data() to test data loading")
    
    # Try to provide specific guidance
    if (file.exists("config.yml")) {
      config <- yaml::read_yaml("config.yml")
      data_dir <- config$data$input_dir
      
      if (!dir.exists(data_dir)) {
        message("  ❌ Data directory not found: ", data_dir)
      } else {
        files <- list.files(data_dir, pattern = "\\.(csv|parquet|feather)$")
        if (length(files) == 0) {
          message("  ❌ No data files found in: ", data_dir)
        } else {
          message("  📄 Found files: ", paste(files, collapse = ", "))
        }
      }
    }
    
    return(NULL)
  })
}

# Run analysis
if (!interactive()) {
  result <- safe_main_analysis()
  if (is.null(result)) {
    quit(status = 1)  # Exit with error code
  }
}
', patient_name, assessment_date)
}