# File: NAMESPACE
# Generated by roxygen2: do not edit by hand

# Main exports
export(DomainProcessorR6)
export(DomainProcessorFactoryR6)
export(TableGTR6)
export(DotplotR6)
export(NeuropsychResultsR6)
export(DuckDBProcessorR6)
export(PackageManagerR6)

# Utility functions
export(create_domain_processor)
export(process_simple_domain)
export(process_multi_rater_domain)
export(batch_process_domains)
export(setup_neuro2_packages)
export(quick_package_check)
export(get_domain_info)
export(check_domain_raters)
export(validate_processor_inputs)

# Workflow functions
export(create_patient_workspace)
export(generate_assessment_report)
export(process_all_domains)

# Import statements
import(R6)
import(dplyr)
import(ggplot2)
importFrom(readr, read_csv, write_csv)
importFrom(gt, gt, gtsave, tab_header, tab_footnote)
importFrom(yaml, read_yaml, write_yaml)
importFrom(here, here)
importFrom(glue, glue, glue_collapse)
importFrom(tidyr, replace_na)
importFrom(purrr, map, map_dfr)
importFrom(stringr, str_detect, str_replace)

# S3 methods
S3method(print, neuro2_results)
S3method(summary, neuro2_results)