patient:
  name: Test Patient
  age: 35.0
  doe: '2025-07-21'
data:
  input_dir: data-raw/csv
  output_dir: data
  format: csv
processing:
  use_duckdb: yes
  parallel: no
report:
  template: template.qmd
  format: html
  output_dir: output
