patient:
  name: Biggie
  age: 18
  dob: "XXXX-XX-XX"
  doe: "2025-01-01"
data:
  input_dir: data-raw/csv
  output_dir: data
  format: all
processing:
  use_duckdb: yes
  parallel: yes
  verbose: yes
  age_group: ""
output:
  generate_qmd: yes
  generate_plots: yes
  generate_tables: yes
report:
  template: template.qmd
  format: neurotyp-pediatric-typst
  output_dir: output
