name: R-CMD-check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        r: ["4.5.0"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up R ${{ matrix.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Quarto smoke test
        run: |
          cat > ci_smoke.qmd <<'Q'
          ---
          title: "CI Smoke"
          format: html
          ---
          Hello Quarto.
          Q
          quarto render ci_smoke.qmd

      - name: Check
        uses: r-lib/actions/check-r-package@v2
        with:
          args: "--no-manual"
          build_args: "--no-manual"
